name       : swig
version    : 4.0.1
release    : 5
source     :
    - https://github.com/swig/swig/archive/rel-4.0.1.tar.gz : 2eaf6fb89d071d1be280bf995c63360b3729860c0da64948123b5d7e4cfb6cb7
license    :
    - GPL-3.0
summary    : SWIG is a software development tool that connects programs written in C and C++ with a variety of high-level programming languages.
component  : programming.tools
description: |
    SWIG is a software development tool that connects programs written in C and C++ with a variety of high-level programming languages.
builddeps  :
    - yodl
setup      : |
    ./autogen.sh --prefix=/usr
    %configure
build      : |
    %make
install    : |
    %make_install
