name       : swig
version    : 3.0.12
release    : 3
source     :
    - https://github.com/swig/swig/archive/rel-3.0.12.tar.gz : 64971de92b8a1da0b9ffb4b51e9214bb936c4dbbc304367899cdb07280b94af6
license    :
    - GPL-3.0
summary    : SWIG is a software development tool that connects programs written in C and C++ with a variety of high-level programming languages.
component  : programming.tools
description: |
    SWIG is a software development tool that connects programs written in C and C++ with a variety of high-level programming languages.
builddeps  :
    - yodl
setup      : |
    ./autogen.sh --prefix=/usr
    %configure
build      : |
    %make
install    : |
    %make_install
