name       : swig
version    : 4.0.2
release    : 6
source     :
    - https://github.com/swig/swig/archive/refs/tags/v4.0.2.tar.gz : b5f43d5f94c57ede694ffe5e805acc5a3a412387d7f97dcf290d06c46335cb0b
homepage   : http://www.swig.org/
license    : GPL-3.0-or-later
component  : programming.tools
summary    : SWIG (Simplified Wrapper and Interface Generator)
description: |
    SWIG is a software development tool that connects programs written in C and C++ with a variety of high-level programming languages. SWIG is primarily used with common scripting languages such as Perl, Python, Tcl/Tk, and Ruby, however the list of supported languages also includes non-scripting languages such as Java, OCAML and C#. Also several interpreted and compiled Scheme implementations (Guile, MzScheme) are supported. SWIG is most commonly used to create high-level interpreted or compiled programming environments, user interfaces, and as a tool for testing and prototyping C/C++ software. SWIG can also export its parse tree in the form of XML.
builddeps  :
    - yodl
setup      : |
    %autogen
build      : |
    %make
install    : |
    %make_install
