name       : swig
version    : 3.0.7
release    : 2
source     :
    - https://github.com/swig/swig/archive/rel-3.0.7.tar.gz : 5df13c6243415d2d065e151b06895ad81556f65483a74424126246b5c385d2ef
license    : 
    - GPL-3.0
summary    : SWIG is a software development tool that connects programs written in C and C++ with a variety of high-level programming languages.
description: |
    SWIG is a software development tool that connects programs written in C and C++ with a variety of high-level programming languages.
builddeps  :
    - yodl
setup      : |
    ./autogen.sh --prefix=/usr
    %configure
build      : |
    %make
install    : |
    %make_install
